### Teste 0: Criar o Servidor Primeiro (Obrigatório porque o banco está zerado)
POST http://localhost:3000/servidor
Content-Type: application/json

{
  "matricula": "12345",
  "nome": "Adriano Analista",
  "cargo": "GESTAO"
}

###

### Teste 1: Criar uma diária para Gestão em Brasília com Pernoite
POST http://localhost:3000/diarias
Content-Type: application/json

{
  "cargo": "GESTAO",
  "destino": "BRASILIA",
  "temPernoite": true,
  "servidorId": 1
}

###

### Teste 2: Criar uma diária Operacional (Bate-volta no interior)
POST http://localhost:3000/diarias
Content-Type: application/json

{
  "cargo": "OPERACIONAL",
  "destino": "CANOAS",
  "temPernoite": false,
  "servidorId": 1
}

###

### Teste 3: Ver todos os pedidos realizados
GET http://localhost:3000/diarias